### ISSUE TITLE
ionic2-jpush 在ios 环境中不工作

### ISSUE THREAD

**Issue by jackytse** [HsuanXyz/ionic2-jpush#1]
HsuanXyz 你好

我在使用 ionic2-jpush 的过程中遇到一个问题，我写的同样一份代码，在Android 设备中能接收到通知，在iOS 设备中不能收到通知。
我在极光后台配置了一个iOS开发环境的p12证书，然后在iOS设备里执行了jPushPlugin 的init 方法，然后在极光后台发送通知，目标平台选择的是iOS开发环境和Android，Android 设备总是能收到通知，iOS 设备收不到通知，并且极光后台推送历史那里 iOS 那一列“目标”和“成功”的数据都是 0。我想可能是客户端init 操作没有成功，调试后发现客户端init 返回的数据是ok。客户端已经设置了允许接收通知。

请教，可能在哪个环节出了问题？

**Comment by hsuanxyz** [comment]
@jackytse 你init之后，尝试获取设备ID。如果有正确返回说明注册成功，否则你需要排除证书和签名相关的问题。

**Comment by jackytse** [comment]
@HsuanXyz 感谢你的回答，问题已经解决了，要打开XCode 在项目中配置一下Push Notifications 为ON 才行。
