### ISSUE TITLE
第一次进入获取不到id

### ISSUE THREAD

**Issue by wangying11** [HsuanXyz/ionic2-jpush#4]

**Comment by hsuanxyz** [comment]
让我看看你初始化部分的代码

**Comment by wangying11** [comment]
ionViewDidLoad() {
    console.log('ionViewDidLoad LoginPage');
    this.init();
    this.getRegistrationID();
  }
  /**
   * 注册极光
   */
  init() {
    this.jPushPlugin.init()
      .then(res => this.presentToast(res))
      .catch(err => alert(err))
  }
  /**
   * 获取ID
   */
  getRegistrationID() {

  
    this.platform.ready().then(() => {
      this.jPushPlugin.getRegistrationID()
        .then(res => {
          this.RegistrationID = res;
          this.presentToast(res)
        })
        .catch(err => alert(err))
    })
  }

**Comment by wangying11** [comment]
我在登陆页这样写的，安卓把进程杀掉，第二次就可以获取id

**Comment by hsuanxyz** [comment]
你有在 `platform.ready` 时调用 `jPushPlugin.init` 吗？
如果没有被 init, 是无法获取设备id的

**Comment by sdandroid** [comment]
有同样的问题app新安装，第一次，获取不到RegistrationID，提示 获取ID失败。

` export class PluginsTestPage {

     RegistrationID: any

    constructor(private platform: Platform,

                private jPushPlugin: JPushService) {

        this.platform.ready().then(() => {

            this.init();

            this.getRegistrationID();

            this.jPushPlugin.openNotification()
                .subscribe(res => {
                    console.log('收到推送');
                    console.log(res)
                });

            this.jPushPlugin.receiveNotification()
                .subscribe(res => {
                    console.log('收到推送');
                    console.log(res)
                });

            this.jPushPlugin.receiveMessage()
                .subscribe(res => {
                    console.log('收到推送');
                    console.log(res)
                });

        })

    }

    /**
     * 注册极光
     */
    init() {
        this.jPushPlugin.init()
            .then(res =>

                      alert(res)
            )
            .catch(err => alert(err))
    }

    /**
     * 获取ID
     */
    getRegistrationID() {
        this.jPushPlugin.getRegistrationID()
            .then(res => {
                      alert(res);
                      this.RegistrationID = res;
                  }
            )
            .catch(err => alert(err))
    }
}`

**Comment by hsuanxyz** [comment]
我上传了一个demo，一切都很正常。你们可以看看
