### ISSUE TITLE
官网升级至3.2.11时，出错（SIGNAL SIGABRT）

### ISSUE THREAD

**Issue by 13868620741** [HsuanXyz/ionic2-jpush#5]
-(void)setAlias:(CDVInvokedUrlCommand*)command {
    /*
    NSDictionary* params = [command.arguments objectAtIndex:0];
    NSNumber* sequence = params[@"sequence"];   (这一行出错：Thread 1 : SIGNAL SIGABRT)
    NSString* alias = params[@"alias"];

**Comment by hsuanxyz** [comment]
@13868620741 感谢你的反馈，近期会同步官方API

**Comment by hsuanxyz** [comment]
请更新到新版本，并查看最新文档。

**Comment by 13868620741** [comment]
非常感谢作者的回复与处理！谢谢

**Comment by coolara** [comment]
亲 怎么增加addLocalNotification 这个方法进去啊
