### ISSUE TITLE
升级官方RXJS 5.5.2后报错了。

### ISSUE THREAD

**Issue by dinglicoding** [HsuanXyz/ionic2-jpush#7]
错误信息：
node_modules/ionic2-jpush/dist/plugin-jpush.service.d.ts, line: 1
Cannot find type definition file for 'core-js'.

       L1:  import { Observable } from 'rxjs/Rx';
       L2:  export declare class JPushService {

Error: Failed to transpile TypeScript
 at errorCheckProgram (~\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:119:39)
    at Object.<anonymous> (～\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:89:21)
    at step (～\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (～\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (～\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)

**Comment by hsuanxyz** [comment]
npm install ionic2-jpush@0.1.1

**Comment by dinglicoding** [comment]
thanks for you replay
我执行了npm install ionic2-jpush@0.1.1
在执行ionic cordova build android --prod --release的时候 报错
Error: ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (\node_modules\typescript\lib\typescript.js:44563:16)
 @ ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76
 @ ./node_modules/rxjs/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/ionic2-jpush/dist/plugin-jpush.service.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (\node_modules\typescript\lib\typescript.js:44563:16)
 @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/ionic2-jpush/dist/plugin-jpush.service.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (\node_modules\webpack\lib\Compiler.js:368:12)
    at next (\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (\node_modules\tapable\lib\Tapable.js:222:13)

**Comment by hsuanxyz** [comment]
让我看看你 `package.json`

**Comment by dinglicoding** [comment]
@HsuanXyz 
如下：
`{
    "name": "a",
    "description": "crown app ionic3",
    "author": "l",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "build": "ionic-app-scripts build",
        "clean": "ionic-app-scripts clean",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "npm run build",
        "ionic:serve": "npm run serve",
        "ionic:lint": "npm run lint"
    },
    "dependencies": {
       "@angular/common": "5.0.0",
        "@angular/compiler": "5.0.0",
        "@angular/compiler-cli": "5.0.0",
        "@angular/core": "5.0.0",
        "@angular/forms": "5.0.0",
        "@angular/http": "5.0.0",
        "@angular/platform-browser": "5.0.0",
        "@angular/platform-browser-dynamic": "5.0.0",
        "@angular/tsc-wrapped": "^4.4.6",
        "@ionic-native/app-update": "4.3.1",
        "@ionic-native/app-version": "4.3.1",
        "@ionic-native/camera": "^4.3.2",
        "@ionic-native/clipboard": "^4.3.2",
        "@ionic-native/core": "4.3.1",
        "@ionic-native/file": "^4.3.2",
        "@ionic-native/file-opener": "^4.3.2",
        "@ionic-native/file-transfer": "^4.3.2",
        "@ionic-native/image-picker": "^4.3.2",
        "@ionic-native/in-app-browser": "4.3.1",
        "@ionic-native/keyboard": "^4.4.0",
        "@ionic-native/photo-viewer": "^4.3.2",
        "@ionic-native/splash-screen": "4.3.1",
        "@ionic-native/status-bar": "4.3.1",
        "@ionic-native/toast": "4.3.1",
        "@ionic/storage": "^2.1.3",
        "cordova-android": "^6.2.3",
        "cordova-clipboard": "^1.1.0",
        "cordova-ios": "^4.5.2",
        "cordova-plugin-app-update": "^1.4.7",
        "cordova-plugin-app-version": "^0.1.9",
        "cordova-plugin-appversion": "^1.0.0",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-console": "^1.1.0",
        "cordova-plugin-device": "^1.1.6",
        "cordova-plugin-file": "^4.0.0",
        "cordova-plugin-file-opener2": "^2.0.19",
        "cordova-plugin-file-transfer": "^1.6.3",
        "cordova-plugin-image-picker": "^1.1.3",
        "cordova-plugin-ionic-webview": "^1.1.16",
        "cordova-plugin-jcore": "^1.1.10",
        "cordova-plugin-screen-orientation": "^2.0.1",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.1",
        "cordova-plugin-whitelist": "^1.3.2",
        "es6-promise-plugin": "git+https://github.com/vstirbu/PromisesPlugin.git",
        "ionic-angular": "3.9.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionic2-jpush": "^0.1.1",
        "ionicons": "3.0.0",
        "jpush-phonegap-plugin": "^3.2.8",
        "rxjs": "^5.5.2",
        "socket.io-client": "^2.0.3",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.0",
        "ionic": "3.16.0",
        "typescript": "2.4.2"
    },
    "config": {
        "ionic_aot_write_to_disk": true
    },
    "cordovaPlugins": [
        "cordova-plugin-splashscreen",
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "ionic-plugin-keyboard",
        "cordova-plugin-app-version"
    ],
    "cordovaPlatforms": [],
    "cordova": {
        "plugins": {
            "cordova-plugin-app-version": {},
            "cordova-plugin-camera": {},
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-file-transfer": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "jpush-phonegap-plugin": {
                "APP_KEY": ""
            },
            "cordova-plugin-app-update": {},
            "cordova-plugin-image-picker": {},
            "cordova-plugin-jcore": {},
            "cordova-clipboard": {},
            "cordova-plugin-screen-orientation": {},
            "cordova-plugin-file": {},
            "cordova-plugin-file-opener2": {},
            "cordova-plugin-ionic-webview": {},
            "ionic-plugin-keyboard": {}
        },
        "platforms": [
            "android"
        ]
    }
}`

**Comment by hsuanxyz** [comment]
请格式化一下

**Comment by dinglicoding** [comment]
{
    "name": "a",
    "description": "crown app ionic3",
    "author": "l",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "build": "ionic-app-scripts build",
        "clean": "ionic-app-scripts clean",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "npm run build",
        "ionic:serve": "npm run serve",
        "ionic:lint": "npm run lint"
    },
    "dependencies": {
       @"angular/common": "5.0.0",
        "angular/compiler": "5.0.0",
        "angular/compiler-cli": "5.0.0",
        "angular/core": "5.0.0",
        "angular/forms": "5.0.0",
        "angular/http": "5.0.0",
        "angular/platform-browser": "5.0.0",
        "angular/platform-browser-dynamic": "5.0.0",
        "angular/tsc-wrapped": "^4.4.6",
        "ionic-native/app-update": "4.3.1",
        "ionic-native/app-version": "4.3.1",
        "ionic-native/camera": "^4.3.2",
        "ionic-native/clipboard": "^4.3.2",
        "ionic-native/core": "4.3.1",
        "ionic-native/file": "^4.3.2",
        "ionic-native/file-opener": "^4.3.2",
        "ionic-native/file-transfer": "^4.3.2",
        "ionic-native/image-picker": "^4.3.2",
        "ionic-native/in-app-browser": "4.3.1",
        "ionic-native/keyboard": "^4.4.0",
        "ionic-native/photo-viewer": "^4.3.2",
        "ionic-native/splash-screen": "4.3.1",
        "ionic-native/status-bar": "4.3.1",
        "ionic-native/toast": "4.3.1",
        "ionic/storage": "^2.1.3",
        "cordova-android": "^6.2.3",
        "cordova-clipboard": "^1.1.0",
        "cordova-ios": "^4.5.2",
        "cordova-plugin-app-update": "^1.4.7",
        "cordova-plugin-app-version": "^0.1.9",
        "cordova-plugin-appversion": "^1.0.0",
        "cordova-plugin-camera": "^2.4.1",
        "cordova-plugin-console": "^1.1.0",
        "cordova-plugin-device": "^1.1.6",
        "cordova-plugin-file": "^4.0.0",
        "cordova-plugin-file-opener2": "^2.0.19",
        "cordova-plugin-file-transfer": "^1.6.3",
        "cordova-plugin-image-picker": "^1.1.3",
        "cordova-plugin-ionic-webview": "^1.1.16",
        "cordova-plugin-jcore": "^1.1.10",
        "cordova-plugin-screen-orientation": "^2.0.1",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.1",
        "cordova-plugin-whitelist": "^1.3.2",
        "es6-promise-plugin": "git+https://github.com/vstirbu/PromisesPlugin.git",
        "ionic-angular": "3.9.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionic2-jpush": "^0.1.1",
        "ionicons": "3.0.0",
        "jpush-phonegap-plugin": "^3.2.8",
        "rxjs": "^5.5.2",
        "socket.io-client": "^2.0.3",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.0",
        "ionic": "3.16.0",
        "typescript": "2.4.2"
    },
    "config": {
        "ionic_aot_write_to_disk": true
    },
    "cordovaPlugins": [
        "cordova-plugin-splashscreen",
        "cordova-plugin-whitelist",
        "cordova-plugin-console",
        "cordova-plugin-statusbar",
        "ionic-plugin-keyboard",
        "cordova-plugin-app-version"
    ],
    "cordovaPlatforms": [],
    "cordova": {
        "plugins": {
            "cordova-plugin-app-version": {},
            "cordova-plugin-camera": {},
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-file-transfer": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "jpush-phonegap-plugin": {
                "APP_KEY": ""
            },
            "cordova-plugin-app-update": {},
            "cordova-plugin-image-picker": {},
            "cordova-plugin-jcore": {},
            "cordova-clipboard": {},
            "cordova-plugin-screen-orientation": {},
            "cordova-plugin-file": {},
            "cordova-plugin-file-opener2": {},
            "cordova-plugin-ionic-webview": {},
            "ionic-plugin-keyboard": {}
        },
        "platforms": [
            "android"
        ]
    }
}
